---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: simple-package-repository
spec:
  syncPeriod: 30m
  fetch:
    imgpkgBundle:
      image: index.docker.io/jkimmelvmware/my-pkg-repo:packages-1.0.0
