---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: simple-package-repository
spec:
  fetch:
    imgpkgBundle:
      image: index.docker.io/jkimmelvmware/toy-projects:artificialtweetener-0.1.0
