apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: artificial-tweetener.github.com.0.1.0
spec:
  syncPeriod: 30m
  refName: artificial-tweetener.github.com
  version: 0.1.0
  releaseNotes: try not to be so jealous
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: index.docker.io/jkimmelvmware/toy-projects:artificialtweetener-0.1.0
      template:
      - ytt:
          paths:
          - "config/"
      -kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}
