apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: artificial-tweetener.github.com.v1
spec:
  refName: artificial-tweetener.github.com
  version: v1
  releaseNotes: try not to be so jealous
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: index.docker.io/jkimmelvmware/toy-projects:artificialtweetener-v1
      template:
      - ytt:
          paths:
          - "config/"
      -kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kap: {}
